### ISSUE TITLE
Question on parameter value

### ISSUE THREAD

**Issue by ritviksahajpal** [WentaoZhan1998/geospaNN#1]
Thanks for this package! I am looking forward to trying it out. Can you provide some guidance/heuristic on what value(s) to use for the nearest neighbor parameter `nn` here:

```
import torch
import geospaNN
import numpy as np

# 1.
def f5(X): return (10*np.sin(np.pi*X[:,0]*X[:,1]) + 20*(X[:,2]-0.5)**2 + 10*X[:,3] +5*X[:,4])/6

p = 5; funXY = f5

# 2.
sigma = 1
phi = 3/np.sqrt(2)
tau = 0.01
theta = torch.tensor([sigma, phi, tau])

# 3.
n = 1000            # Size of the simulated sample.
nn = 20             # Neighbor size used for NNGP.
batch_size = 50     # Batch size for training the neural networks.
```

i.e. do you suggest `nn` as a function of dataset size or selecting value based on sensitivity analysis? 

Thanks!

**Comment by WentaoZhan1998** [comment]
Thanks for considering using our package. Usually we recommend people use nn=20 for sample size between 100 to 100000. Larger nn will always improve the approximation but cost more time. From our experience, with a reasonable sample size (100 to 100000), a larger nn than 20 does not bring significant improvement in estimation and prediction.

Feel free to let us know if you have any further questions.

**Comment by ritviksahajpal** [comment]
Thank you! this is helpful!
